# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - amoce

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_90e12a0da01d453994746131d04a3c3b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c208c9a633644f97af27a2e4d191f6f8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_90e12a0da01d453994746131d04a3c3b }}/aurea_moce:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'amoce'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f0b1c2dd8b0480ab87a61c7e3e75c03 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_90e12a0da01d453994746131d04a3c3b }}/aurea_moce:${{ github.sha }}'